# Generated by Django 5.1.7 on 2025-03-19 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bolim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('is_avtive', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Habar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('mindef', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('view', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(default='habar_img/default.jpg', upload_to='habar_img')),
                ('bolim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habar.bolim')),
            ],
        ),
    ]
