# Generated by Django 5.1.7 on 2025-03-21 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='sponsor_img/')),
                ('is_active', models.BooleanField()),
            ],
        ),
    ]
