# Generated by Django 5.1.7 on 2025-03-21 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habar', '0002_sponsor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('sent_date', models.DateTimeField(auto_now_add=True)),
                ('view', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Contacts',
                'ordering': ['view'],
            },
        ),
    ]
